spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    properties:
      schema:
        registry:
          url: ${KAFKA_SCHEMA_REGISTRY:http://localhost:8081}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
